before_script:
    - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
    - apt-get update -qq && apt-get install --yes -qq cmake python3 scons valgrind

stages:
    - build

build_all:
    script: "./exec.py distclean init build --target all"
    stage: build
