before_script:
    - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
    - apt-get update -qq && apt-get install --yes -qq cmake python3 scons valgrind gcc clang cppcheck

stages:
    - build
    - test

build-all:
    script: "./exec.py init build --target all --compiler gcc clang"
    stage: build

unittest:
    script: "./exec.py init build run --target all --run unittest --compiler gcc clang"
    stage: test

run-benchmarks-gcc:
    script: "./exec.py init build run --target all --run performance --compiler gcc"
    stage: test

run-benchmarks-clang:
    script: "./exec.py init build run --target all --run performance --compiler clang"
    stage: test

valgrind:
    script: "./exec.py init build run --target all --run unittest --valgrind --compiler gcc clang"
    stage: test

cppcheck:
    script: "./exec.py init analyze -a cppcheck"
    stage: test

clang-static-analyzer:
    script: "./exec.py distclean init analyze -a clang"
    stage: test
