before_script:
    - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
    - apt-get update -qq && apt-get install --yes -qq cmake scons gcc clang

stages:
    - build
    - test

build-all:
    script: 
        - git submodule update --init 3rdparty/exec-helper
        - "./exec init build --target all --compiler gcc clang"
    stage: build

unittest:
    script: "./exec init build run --target all --run unittest --compiler gcc clang"
    stage: test

run-benchmarks-gcc:
    script: "./exec init build run --target all --run performance --compiler gcc"
    stage: test

run-benchmarks-clang:
    script: "./exec init build run --target all --run performance --compiler clang"
    stage: test

valgrind:
    script: 
        - apt-get install --yes -qq valgrind
        - "./exec init build analyze --target all --run unittest --analyze-method valgrind --compiler gcc clang"
    stage: test

cppcheck:
    script: 
        - apt-get install --yes -qq cppcheck unzip
        - "./exec analyze -a cppcheck"
    stage: test

clang-static-analyzer:
    script: "./exec init analyze -a clang"
    stage: test

pmd-cpd:
    script: 
        - apt-get install --yes -qq default-jre unzip
        - "./exec analyze -a cpd"
    stage: test

perf-profiling:
    script:
        - apt-get install --yes -qq unzip flex bison
        - wget https://github.com/torvalds/linux/archive/master.zip && unzip master.zip && pushd linux-master/tools/perf && make && export PATH=$PATH:$(pwd); popd
        - ./exec init build profile --profile-method perf -r performance
    stage: test
