before_install:
    #    - sudo apt-get -qq update
    #    - sudo apt-get install -y cmake python3 valgrind
# Use sed to replace the SSH URL with the public URL, then initialize submodules
before_install:
    - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules

addons:
    apt:
        packages:
            - cmake
            - python3
            - valgrind

language: c++

env:
    - EXEC='distclean init build --target all'
    - EXEC='distclean init build run --run unittest --target all'
    - EXEC='distclean init build run --valgrind --run unittest --target all'
    - EXEC='distclean init build run --run performance --target all'

script: ./exec $EXEC

compiler: 
    - gcc
    - clang

## Hacks to make Travis handle git submodules properly
# Handle git submodules yourself
git:
    submodules: false

# Require for apt
sudo: required

# Hack to get a more up to date version of CMake
dist: trusty
