before_install:
    #    - sudo apt-get -qq update
    #    - sudo apt-get install -y cmake python3 valgrind
# Use sed to replace the SSH URL with the public URL, then initialize submodules
before_install:
    - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules

install:
    # Install more recent clang
    - wget 'llvm.org/releases/3.8.0/clang+llvm-3.8.0-x86_64-linux-gnu-ubuntu-14.04.tar.xz' && tar -xf 'clang+llvm-3.8.0-x86_64-linux-gnu-ubuntu-14.04.tar.xz' && export PATH=$(pwd)/clang+llvm-3.8.0-x86_64-linux-gnu-ubuntu-14.04/bin:$PATH

addons:
    apt:
        packages:
            - cmake
            - python3
            - scons
            - valgrind
            - cppcheck
            - wget

language: c++

env:
    - EXEC='init build --target all'
    - EXEC='init build run --run unittest --target all'
    - EXEC='init build run --valgrind --run unittest --target all'
    - EXEC='init build run --run performance --target all'
    - EXEC='init analyze -a cppcheck'
    - EXEC='init analyze -a clang'

script: 
    - ./exec $EXEC


compiler: 
    - gcc
    - clang

## Hacks to make Travis handle git submodules properly
# Handle git submodules yourself
git:
    submodules: false

# Require for apt
sudo: required

# Hack to get a more up to date version of CMake
dist: trusty
