before_install:
    #    - sudo apt-get -qq update
    #    - sudo apt-get install -y cmake python3 valgrind
# Use sed to replace the SSH URL with the public URL, then initialize submodules
before_install:
    - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules

install:
    # Install more recent clang
    - wget 'llvm.org/releases/3.8.0/clang+llvm-3.8.0-x86_64-linux-gnu-ubuntu-14.04.tar.xz' && tar -xf 'clang+llvm-3.8.0-x86_64-linux-gnu-ubuntu-14.04.tar.xz' && export PATH=$(pwd)/clang+llvm-3.8.0-x86_64-linux-gnu-ubuntu-14.04/bin:$PATH
    # Install latest cppcheck
    - wget https://github.com/danmar/cppcheck/archive/master.zip && unzip master.zip && make -C cppcheck-master -j SRCDIR=build CFGDIR=cfg HAVE_RULES=yes CXXFLAGS="-O2 -DNDEBUG -Wall -Wno-sign-compare -Wno-unused-function" && export PATH=$(pwd)/cppcheck-master:$PATH

addons:
    apt:
        packages:
            - cmake
            - python3
            - scons
            - valgrind
            - wget

language: c++

compiler: gcc

env:
    - EXEC='init build --target all --compiler gcc'
    - EXEC="init build --target all --compiler clang --toolchain-path ${PWD}/clang+llvm-3.8.0-x86_64-linux-gnu-ubuntu-14.04/bin"
    - EXEC='init build run --compiler gcc --run unittest --target all'
    - EXEC="init build run --compiler clang --run unittest --target all --toolchain-path ${PWD}/clang+llvm-3.8.0-x86_64-linux-gnu-ubuntu-14.04/bin"
    - EXEC='init build run --compiler gcc --valgrind --run unittest --target all'
    - EXEC="init build run --compiler clang --valgrind --run unittest --target all --toolchain-path ${PWD}/clang+llvm-3.8.0-x86_64-linux-gnu-ubuntu-14.04/bin"
    - EXEC='init build run --compiler gcc --run performance --target all'
    - EXEC="init build run --compiler clang --run performance --target all --toolchain-path ${PWD}/clang+llvm-3.8.0-x86_64-linux-gnu-ubuntu-14.04/bin"
    - EXEC='init analyze -a cppcheck'
    - EXEC='init analyze -a clang'

script: 
    - PWD=$(pwd) ./exec $EXEC

## Hacks to make Travis handle git submodules properly
# Handle git submodules yourself
git:
    submodules: false

# Require for apt
sudo: required

# Hack to get a more up to date version of CMake
dist: trusty
